start partials\plot_0.bat
start partials\plot_1.bat
start partials\plot_2.bat
start partials\plot_3.bat
start partials\plot_4.bat
start partials\plot_5.bat
start partials\plot_6.bat
start partials\plot_7.bat
start partials\plot_8.bat
start partials\plot_9.bat
