start partials_fetch\fetch_0.bat
start partials_fetch\fetch_1.bat
start partials_fetch\fetch_2.bat
start partials_fetch\fetch_3.bat
start partials_fetch\fetch_4.bat
start partials_fetch\fetch_5.bat
start partials_fetch\fetch_6.bat
start partials_fetch\fetch_7.bat
start partials_fetch\fetch_8.bat
start partials_fetch\fetch_9.bat
